import type { ValidationRow } from './references';
import rows from './generated/phase6_library.json';

/**
 * The molecule library (spec Phase 6). Generated by
 * tools/molecules/build_library.py from the meta.json files that ship, so
 * `app` is exactly what the app displays; tools/molecules/tests/
 * test_library_data.py fails if this file falls out of date. Ozone's
 * dipole row carries `knownMiss` (ruling T7-O3): a documented exception,
 * not a hidden failure.
 */
export const PHASE_6_ROWS: ValidationRow[] = rows as ValidationRow[];
