import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import ProvenancePanel from '../../src/components/ProvenancePanel';
import TierBadge from '../../src/components/TierBadge';
import type { MoleculeProvenance } from '../../src/molecules/types';
import type { LibraryMoleculeMeta } from '../../src/molecules/library_types';
import { waterMeta } from '../molecules/fixtures';
import { jobFixture } from './api_fixtures';

const KEY = jobFixture('get_done').key;
/** What build_library and the 6B-1 worker write since the TZVPD switch (the shared waterMeta fixture predates it). */
const TZVPD = { density: 'B3LYP/def2-TZVPD', energies: 'B3LYP/def2-TZVPD' };
const PROVENANCE: MoleculeProvenance = {
    jobKey: KEY, computeVersion: 1, recipe: 'single',
    geometrySource: { kind: 'pubchem', cid: 962, title: 'Water', query: 'water', retrievedAt: '2026-10-10' },
    caveats: ["The geometry is not optimised: it is PubChem's computed 3D conformer or as pasted."],
    generatorCommit: 'abc1234def567', imageDigest: 'local', pyscfVersion: '2.8.0', sizingVersion: 1, size: 'S',
    capacity: 'local', wallSeconds: 70.2, costUsd: null,
};
const computed = (over: Partial<MoleculeProvenance> = {}, extra: Record<string, unknown> = {}): LibraryMoleculeMeta =>
    waterMeta({ id: KEY, tier: 'computed', method: TZVPD, provenance: { ...PROVENANCE, ...over }, references: [], ...extra });
const open = () => fireEvent.click(screen.getByRole('button', { name: 'How this was computed' }));

describe('TierBadge', () => {
    it('names the tier and says what it means', () => {
        const { rerender } = render(<TierBadge tier="validated" />);
        expect(screen.getByRole('note', { name: 'data tier' })).toHaveTextContent('ValidatedCurated, and checked against published values.');
        rerender(<TierBadge tier="computed" />);
        expect(screen.getByRole('note', { name: 'data tier' }))
            .toHaveTextContent('ComputedComputed on request by the same method; not benchmarked against experiment.');
    });
});

describe('ProvenancePanel', () => {
    it('states a validated molecule’s method, its geometry and what it was checked against', () => {
        render(<ProvenancePanel meta={waterMeta({ method: TZVPD })} ownerJob={null} />);
        open();
        expect(screen.getByText('Method: B3LYP/def2-TZVPD, PySCF 2.6.0.')).toBeInTheDocument();
        expect(screen.getByText('Geometry: experiment (CCCBDB).')).toBeInTheDocument();
        expect(screen.getByText('dipole: 1.855 D — CRC Handbook, via CCCBDB')).toBeInTheDocument();
        expect(screen.getByText(/Generated by tools\/molecules\/build_library\.py at commit abc1234\./)).toBeInTheDocument();
        expect(screen.queryAllByRole('link')).toHaveLength(0);
    });
    it('links a computed molecule’s PubChem record, states its caveats, and links its four files', () => {
        render(<ProvenancePanel meta={computed()} ownerJob={null} />);
        open();
        expect(screen.getByText('Method: B3LYP/def2-TZVPD, PySCF 2.8.0.')).toBeInTheDocument();
        expect(screen.getByRole('link', { name: '962' })).toHaveAttribute('href', 'https://pubchem.ncbi.nlm.nih.gov/compound/962');
        expect(screen.getByText(/its computed 3D conformer, retrieved 2026-10-10, not optimised\./)).toBeInTheDocument();
        expect(screen.getByText(PROVENANCE.caveats[0])).toBeInTheDocument();
        for (const name of ['input.py', 'output.log', 'geometry.xyz', 'job.json']) {
            expect(screen.getByRole('link', { name })).toHaveAttribute('href', `/molecules/jobs/${KEY}/${name}`);
        }
        expect(screen.getByText(/Ran on This Mac: 1 min 10 s of wall time\. Generator commit abc1234; sized by sizing rule v1\./)).toBeInTheDocument();
        expect(screen.queryByText(/Cost:/)).toBeNull();
    });
    it('says an optimised geometry was optimised, from what, and adds the trajectory', () => {
        render(<ProvenancePanel meta={computed({ recipe: 'optimise', geometrySource: { kind: 'xyz' } }, { geometryOptimisation: { steps: 7, converged: true } })} ownerJob={null} />);
        open();
        expect(screen.getByText(/optimised at B3LYP\/def2-SVP with geomeTRIC in 7 steps, starting from pasted XYZ coordinates\./)).toBeInTheDocument();
        expect(screen.getByRole('link', { name: 'trajectory.xyz' })).toHaveAttribute('href', `/molecules/jobs/${KEY}/trajectory.xyz`);
    });
    it('says a resumed optimisation attempt and its step count (D10)', () => {
        render(<ProvenancePanel meta={computed({ recipe: 'optimise', geometrySource: { kind: 'xyz' } }, { geometryOptimisation: { steps: 3, converged: true, resumedFrom: 1 } })} ownerJob={null} />);
        open();
        expect(screen.getByText(/resumed from attempt 1/)).toBeInTheDocument();
    });
    it('shows the owner the time against its prediction, and the cost', () => {
        render(<ProvenancePanel meta={computed()} ownerJob={jobFixture('get_done')} />);
        open();
        expect(screen.getByText(/Owner only: 1 min 10 s of wall time, peak memory 0\.52 GB \(predicted .+ sizing v\d+ prediction\)\./)).toBeInTheDocument();
        expect(screen.getByText(/Cost: spent \$0\.00 \(This Mac\)\./)).toBeInTheDocument();
    });
    it('shows a cost not settled yet as reserved', () => {
        render(<ProvenancePanel meta={computed()} ownerJob={{ ...jobFixture('get_done'), backend: 'aws', actualUsd: null, reservedUsd: 0.0894 }} />);
        open();
        expect(screen.getByText(/Cost: reserved \$0\.09, not settled yet\./)).toBeInTheDocument();
    });
    it('says when the owner’s job record could not be read', () => {
        render(<ProvenancePanel meta={computed()} ownerJob={null} ownerJobError="offline" />);
        open();
        expect(screen.getByRole('alert')).toHaveTextContent('The job record could not be read: offline');
    });
});
