"""Renders input.py: the exact PySCF script a job runs (spec §8.3).

The worker writes this file and then executes it, so what the owner reads
is what ran, not a description of it. It runs on its own with PySCF and
geomeTRIC installed and reproduces the SCF; grids, ESP and the orbital table
come from tools/molecules/build_library.py at the commit in provenance.
"""
from jobs.elements import SYMBOLS

TEMPLATE = '''"""Job {key}

Recipe {recipe}: {description}
Reproduce with PySCF 2.8 and geomeTRIC installed:  python input.py
Generated by electron-orbital-viewer tools/jobs (spec 2026-10-05 on-demand generation).
"""
from pyscf import dft, gto

ATOMS = {atoms}   # Å
CHARGE = {charge}
SPIN = {spin}   # 2S = multiplicity - 1
XC = {xc!r}
BASIS = {basis!r}
OPTIMISE_BASIS = {optimise_basis!r}
MAX_STEPS = 100
MAX_CYCLES = (100, 200, 50)   # DIIS, level shift, second order
LOG = 'output.log'
_log = None


class SCFNotConverged(RuntimeError):
    pass


class OptimisationNotConverged(RuntimeError):
    pass


def _quiet(stage, energy=None):
    pass


def molecule(atoms, basis):
    global _log
    mol = gto.M(atom=atoms, unit='Angstrom', basis=basis, charge=CHARGE, spin=SPIN, symmetry=True, verbose=0)
    _log = _log or open(LOG, 'a')     # one log for every molecule built, appended in order
    mol.stdout, mol.verbose = _log, 4
    return mol


def make_dft(mol):
    # As tools/molecules/optimise.make_dft: RKS for closed shells, ROKS (one orbital set) for open ones.
    mf = dft.RKS(mol) if mol.spin == 0 else dft.ROKS(mol)
    mf.xc = XC
    mf.grids.level = 4
    mf.conv_tol = 1e-10
    return mf


def converge(mol, on_stage):
    rungs = (('DIIS', {{}}), ('level shift 0.3 Ha', {{'level_shift': 0.3}}), ('second-order', None))
    dm = None
    for (label, options), cycles in zip(rungs, MAX_CYCLES):
        stage = f'SCF ({{label}})'
        on_stage(stage, None)
        mf = make_dft(mol)
        if options is None:
            mf = mf.newton()
        else:
            for name, value in options.items():
                setattr(mf, name, value)
        mf.max_cycle = cycles
        mf.callback = lambda env, stage=stage: on_stage(stage, env.get('e_tot'))
        mf.kernel(dm0=dm)
        if mf.converged:
            return mf
        dm = mf.make_rdm1()
    raise SCFNotConverged('SCF did not converge (DIIS, level shift 0.3 Ha, second-order)')


def optimise(atoms, on_stage, on_step):
    from pyscf.geomopt.geometric_solver import kernel as geometric_kernel
    mol = molecule(atoms, OPTIMISE_BASIS)
    steps = []

    def callback(envs):
        m = envs['mol']
        coords = m.atom_coords(unit='Angstrom')
        frame = [(m.atom_pure_symbol(i), tuple(float(c) for c in coords[i])) for i in range(m.natm)]
        steps.append(frame)
        on_stage(f'optimisation step {{len(steps)}}', float(envs['energy']))
        on_step(len(steps), float(envs['energy']), frame)

    try:
        converged, mol_eq = geometric_kernel(make_dft(mol), maxsteps=MAX_STEPS, callback=callback)
    except Exception as e:      # geomeTRIC raises its own NotConvergedError past MAX_STEPS
        raise OptimisationNotConverged(f'optimisation did not converge in {{MAX_STEPS}} steps ({{e}})')
    if not converged:
        raise OptimisationNotConverged(f'optimisation did not converge in {{MAX_STEPS}} steps')
    coords = mol_eq.atom_coords(unit='Angstrom')
    final = [(mol_eq.atom_pure_symbol(i), tuple(float(c) for c in coords[i])) for i in range(mol_eq.natm)]
    return final, {{'steps': len(steps), 'converged': True}}


def build(on_stage=_quiet, on_step=lambda step, energy, atoms: None, start=None):
    atoms, info = (start or ATOMS), {{}}
    if OPTIMISE_BASIS:
        atoms, info = optimise(atoms, on_stage, on_step)
    mol = molecule(atoms, BASIS)
    mf = converge(mol, on_stage)
    return mol, mf, info


if __name__ == '__main__':
    mol, mf, info = build(on_stage=lambda stage, energy=None: print(stage, '' if energy is None else energy))
    print('E =', mf.e_tot, 'Ha', info)
'''

DESCRIPTIONS = {
    'single': 'one B3LYP SCF at the given geometry',
    'optimise': 'B3LYP geomeTRIC optimisation in OPTIMISE_BASIS, then one SCF in BASIS',
}


def render_input(job: dict, key: str, start=None) -> str:
    mol, method = job['molecule'], job['method']
    atoms = start or [(SYMBOLS[a[0] - 1], (a[1], a[2], a[3])) for a in mol['atoms']]
    return TEMPLATE.format(key=key, recipe=job['recipe'], description=DESCRIPTIONS[job['recipe']],
                           atoms=repr([(s, tuple(float(c) for c in xyz)) for s, xyz in atoms]),
                           charge=mol['charge'], spin=mol['multiplicity'] - 1, xc=method['xc'],
                           basis=method['basis'], optimise_basis=method['optimiseBasis'])
